In [1]:
"""
  1) Replace all odd numbers in arr with -1 without changing arr
  2) Convert a 1D array to a 2D array with 2 rows
  3) Iterate through the array and find the sum of all element
"""
import numpy as np
arr = np.arange(10)  # It is arrange not arrange
out = np.where(arr % 2  == 1, -1, arr)
print(arr)
print(out)
#1D to 2D
new_array = arr.reshape(2, -1)# -1 for if I do not know about column
print(new_array)
# Sum
sum = 0
for x in range(0, len(arr)):
  sum = sum + arr[x]
print(sum)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[0 1 2 3 4]
 [5 6 7 8 9]]
45
